# Generated by Django 3.2.4 on 2021-06-20 21:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('shortDescription', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('image', models.FileField(upload_to='image/')),
                ('price', models.FloatField()),
                ('delivery', models.FloatField()),
                ('discount', models.FloatField()),
                ('inStock', models.IntegerField()),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('mark', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('mmyy', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('message', models.TextField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Demand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('price', models.FloatField()),
                ('delivery', models.FloatField()),
                ('advancement', models.CharField(max_length=20)),
                ('partNumber', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
            ],
        ),
        migrations.CreateModel(
            name='SlideShow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to='slidshow/')),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('is_client', models.BooleanField(default=False)),
                ('is_trader', models.BooleanField(default=False)),
                ('numCard', models.CharField(max_length=15, null=True)),
                ('phoneNumber', models.CharField(max_length=15, null=True)),
                ('address', models.TextField(null=True)),
                ('imageProfile', models.FileField(null=True, upload_to='profile/')),
                ('isBlocked', models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Case',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('maxLengthGraphicCard', models.PositiveIntegerField()),
                ('maxHeightCPUfan', models.PositiveIntegerField()),
                ('maxLengthPowerSupply', models.PositiveIntegerField()),
                ('maxLengthMotherboard', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='CPU',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('processorModel', models.CharField(max_length=15)),
                ('pocessorSupport', models.CharField(max_length=10)),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='DisqueDur',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('type', models.CharField(choices=[('SSD', 'ssd'), ('HDD', 'hdd')], max_length=30)),
                ('capacity', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='Fan',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('processorSupport', models.CharField(max_length=255)),
                ('Length', models.PositiveIntegerField()),
                ('Width', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='GraphicCard',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('bus', models.CharField(max_length=30)),
                ('videoMemorySize', models.PositiveIntegerField()),
                ('typeMemory', models.CharField(max_length=30)),
                ('Length', models.PositiveIntegerField()),
                ('Width', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='Motherboard',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('processorSupport', models.CharField(max_length=10)),
                ('frequencyMemory', models.CharField(max_length=255)),
                ('typeMemory', models.CharField(max_length=10)),
                ('maximumRAMslot', models.PositiveIntegerField()),
                ('slotNumber', models.PositiveIntegerField()),
                ('connectorGraphic', models.CharField(max_length=255)),
                ('audioChipset', models.CharField(max_length=10)),
                ('networkStandard', models.CharField(max_length=255)),
                ('Length', models.PositiveIntegerField()),
                ('Width', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='NetworkCard',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('networkStandard', models.CharField(max_length=255)),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='PowerSupply',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('Length', models.PositiveIntegerField()),
                ('Width', models.PositiveIntegerField()),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='RAM',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('capacity', models.PositiveIntegerField()),
                ('frequencyMemory', models.CharField(max_length=10)),
                ('typeMemory', models.CharField(max_length=10)),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='SoundCard',
            fields=[
                ('article_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.article')),
                ('audioChipset', models.CharField(max_length=10)),
            ],
            bases=('edlshop.article',),
        ),
        migrations.CreateModel(
            name='TellMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
                ('usernameCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='ShoppingCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('partNumber', models.IntegerField()),
                ('price', models.FloatField()),
                ('delivery', models.FloatField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review', models.TextField()),
                ('dateAdded', models.DateTimeField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Return',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField(default=django.utils.timezone.now)),
                ('codeReturn', models.IntegerField()),
                ('isAccepted', models.BooleanField(default=False, null=True)),
                ('demand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.demand')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('dateAdded', models.DateTimeField()),
                ('usernameFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.IntegerField()),
                ('dateAdded', models.DateTimeField()),
                ('usernameUser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('vue', models.BooleanField()),
                ('Text', models.TextField()),
                ('image_url', models.URLField()),
                ('url', models.URLField()),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.CreateModel(
            name='MoneyBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('dateAdded', models.DateTimeField()),
                ('cardFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardfrom', to='edlshop.card')),
                ('cardTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardto', to='edlshop.card')),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateAdded', models.DateTimeField()),
                ('articleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
                ('usernameCustomer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
        ),
        migrations.AddField(
            model_name='demand',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user'),
        ),
        migrations.AddField(
            model_name='card',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user'),
        ),
        migrations.AddField(
            model_name='article',
            name='category',
            field=models.ManyToManyField(related_name='category', to='edlshop.Category'),
        ),
        migrations.AddField(
            model_name='article',
            name='usernameTrader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user'),
        ),
        migrations.CreateModel(
            name='UserReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.report')),
                ('usernameReported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
            bases=('edlshop.report',),
        ),
        migrations.CreateModel(
            name='TraderReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.review')),
                ('usernameTrader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
            bases=('edlshop.review',),
        ),
        migrations.CreateModel(
            name='TraderRate',
            fields=[
                ('rate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.rate')),
                ('usernameTrader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.user')),
            ],
            bases=('edlshop.rate',),
        ),
        migrations.CreateModel(
            name='DemandReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.report')),
                ('demandRaported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.demand')),
            ],
            bases=('edlshop.report',),
        ),
        migrations.CreateModel(
            name='ArticleReview',
            fields=[
                ('review_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.review')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
            ],
            bases=('edlshop.review',),
        ),
        migrations.CreateModel(
            name='ArticleReport',
            fields=[
                ('report_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.report')),
                ('articleRaported', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
            ],
            bases=('edlshop.report',),
        ),
        migrations.CreateModel(
            name='ArticleRate',
            fields=[
                ('rate_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='edlshop.rate')),
                ('ArticleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edlshop.article')),
            ],
            bases=('edlshop.rate',),
        ),
    ]
