# Generated by Django 3.2.4 on 2021-06-21 21:48

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edlshop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
