# Generated by Django 3.2.4 on 2021-06-21 22:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('edlshop', '0002_alter_rate_dateadded'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tellme',
            name='dateAdded',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
