# Generated by Django 3.2.4 on 2021-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('edlshop', '0003_alter_tellme_dateadded'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='isConsulted',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
