# Generated by Django 3.2.4 on 2021-06-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Card',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNumber', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('mmyy', models.CharField(max_length=5)),
                ('cvv', models.CharField(max_length=3)),
                ('sold', models.FloatField(default=0)),
                ('isblocked', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='MoneyBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.FloatField()),
                ('dateAdded', models.DateTimeField()),
                ('cardFrom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardfrom', to='edlbank.card')),
                ('cardTo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cardto', to='edlbank.card')),
            ],
        ),
    ]
